events {}
http {
    server {
        listen 80;
        root /data;
        client_max_body_size 100m;
        auth_basic "compat";
        auth_basic_user_file /etc/nginx/htpasswd;
        dav_methods PUT DELETE MKCOL;
        create_full_put_path on;
    }
}
